baseURL = 'https://maxxboese.github.io/'
locale = 'en-us'
title = 'MaxxBoese Portfolio'
theme = 'PaperMod'

[params]
  defaultTheme = "dark"
  
  [params.profileMode]
    enabled = true
    title = "Maxx Boese"
    subtitle = "Cybersecurity Student | Developer"